### ISSUE TITLE
lfe.mk webpage missing

### ISSUE THREAD

**Issue by jchassoul** [ninenines/lfe.mk#5]
https://lfe.mk (beam.mk?) missing )= and since there is no direct link to a plugin section in the erlang.mk landpage the flow/steps to get lfe running with erlang.mk are a little confusing just for lack of information, hope lfe and erlang.mk make a great combo, and the use of erlang.mk with lfe a common pattern.

**Comment by essen** [comment]
Yeah it's mostly a tiny experimental project at this point. It needs real users. https://git.ninenines.eu/lfe.mk.git/

**Comment by essen** [comment]
Looking forward to your feedback! Closing.
